apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  htpasswd: |
    {{- .Values.secrets.htpasswd | nindent 4}}

