{{- if .Values.persistence.enabled}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
provisioner: {{ .Values.storageClass.provisioner}}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode}}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy}}
{{- end }}